### ISSUE TITLE
NPE in Android Studio 1.2.1

### ISSUE THREAD

**Issue by eugene-krivobokov** [mcharmas/android-parcelable-intellij-plugin#34]
Doesn't work in Android Studio 1.2.1

```
null
java.lang.NullPointerException
	at pl.charmas.parcelablegenerator.util.PsiUtils.isOfType(PsiUtils.java:77)
	at pl.charmas.parcelablegenerator.typeserializers.ListSerializerFactory.getSerializer(ListSerializerFactory.java:27)
	at pl.charmas.parcelablegenerator.typeserializers.ChainSerializerFactory.getSerializer(ChainSerializerFactory.java:35)
	at pl.charmas.parcelablegenerator.CodeGenerator.getSerializerForType(CodeGenerator.java:96)
	at pl.charmas.parcelablegenerator.CodeGenerator.generateWriteToParcel(CodeGenerator.java:87)
	at pl.charmas.parcelablegenerator.CodeGenerator.generate(CodeGenerator.java:111)
	at pl.charmas.parcelablegenerator.ParcelableAction$1.run(ParcelableAction.java:50)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:166)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at pl.charmas.parcelablegenerator.ParcelableAction.generateParcelable(ParcelableAction.java:47)
	at pl.charmas.parcelablegenerator.ParcelableAction.actionPerformed(ParcelableAction.java:42)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

**Comment by mcharmas** [comment]
Please check if it still happens with 0.6.2 (probably still in review by jetbrains).
Reopen this issue if you still have problems with plugin.
