### ISSUE TITLE
Android Studio 3.0 not work 

### ISSUE THREAD

**Issue by bubblexin** [mcharmas/android-parcelable-intellij-plugin#71]
Install it on Android Studio3.0，is not work correctly.Have a plugin error prompt.

**Comment by mcharmas** [comment]
From my perspective everything works on Android Studio 3.

Could you provide error stacktrace and code example on which it doesn't work?

**Comment by bubblexin** [comment]
![image](https://user-images.githubusercontent.com/16681982/33596852-49038718-d9d8-11e7-9ef2-6ba846d57c61.png)

**Comment by bubblexin** [comment]
The IDE has the following error

**Comment by mcharmas** [comment]
Thanks,
unfortunately I am unable to reproduce it. This happens when you click generate? Did you try reinstalling plugin?

**Comment by bubblexin** [comment]
Thank you for you answer first.Yeah,this happens when I click generate.I had try reinstalling plugin,but it also not work correctly.Anything else I can try?

**Comment by mcharmas** [comment]
Please send me information about exact IDE version and environment. You will find it in the menu. Place will depend on your os. My env example:

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by bubblexin** [comment]
The information as followes:  

Android Studio 3.0
Build #AI-171.4408382, built on October 21, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

**Comment by mcharmas** [comment]
The only difference is Android Studio version and MacOS version which I cannot update right now. Try updating Android Studio to 3.0.1. I'll try to test it out after updating MacOS to sierra... No idea what is wrong.

**Comment by bubblexin** [comment]
I also have this problem when I updated Android Studio version to 3.0.1.MacOS High Sierra has many compatibility issues...

**Comment by aivision369** [comment]
i face the same issue and below is the error log. Please anyone can help then thanks.

> class with name 'pl.charmas.parcelablegenerator.ParcelableAction' not found [Plugin: pl.charmas.parcelablegenerator]
> com.intellij.diagnostic.PluginException: class with name 'pl.charmas.parcelablegenerator.ParcelableAction' not found [Plugin: pl.charmas.parcelablegenerator]
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.error(ActionManagerImpl.java:195)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:157)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:487)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:475)
> 	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
> 	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
> 	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:47)
> 	at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:40)
> 	at com.intellij.codeInsight.generation.actions.GenerateAction.update(GenerateAction.java:65)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:131)
> 	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:234)
> 	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:179)
> 	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:204)
> 	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:99)
> 	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:340)
> 	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:98)
> 	at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:4443)
> 	at com.intellij.openapi.editor.impl.EditorImpl.access$9500(EditorImpl.java:135)
> 	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3515)
> 	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3421)
> 	at java.awt.Component.processMouseEvent(Component.java:6541)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.lang.ClassNotFoundException: pl.charmas.parcelablegenerator.ParcelableAction PluginClassLoader[pl.charmas.parcelablegenerator, 0.7.0]
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
> 	... 52 more
